language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - yes | sdkmanager "build-tools;28.0.3"
before_script:
  - chmod +x gradlew
  - chmod +x checkstyle/checkstyle.sh
  - chmod +x publishAutotrackerPluginToMavenLocal.sh

script:
  - bash ./publishAutotrackerPluginToMavenLocal.sh
  - bash ./checkstyle/checkstyle.sh
  - ./gradlew test
  - ./gradlew assemble