name: CI

on:
  push:
    
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Before script
        run: |
          chmod +x gradlew
          chmod +x checkstyle/checkstyle.sh
          chmod +x publishAutotrackerPluginToMavenLocal.sh

      - name: Run Gradle command
        run: |
          bash ./publishAutotrackerPluginToMavenLocal.sh
          bash ./checkstyle/checkstyle.sh
          ./gradlew test
          
